services:
  - type: web
    name: miradx_api
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: miradx_production
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_ENV
        value: production

databases:
  - name: miradx_production
    databaseName: miradx_production_tlo1
    user: miradx_production_user
    plan: free
