services:
  - type: web
    name: miradx-risk-analysis-api-test
    runtime: ruby
    buildCommand: "echo 'Testing build command' && ./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: miradx_production
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: miradx-risk-analysis-db
    databaseName: miradx_production
    user: miradx_production_user
    plan: free
